name: Run Linter
on:
  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Entering "app" directory
      run: cd app

    - name: Installing modules
      run: yarn

    - name: Running linter
      run: yarn lint